name: hushh_for_students_ios
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.25.0+25

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  firebase_core: ^3.4.0
  package_info_plus: ^8.0.2
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.0
  flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.6.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  date_format: ^2.0.9
  intl: ^0.19.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/oac.jpg
    - lib/assets/thapa.jpg
    - lib/assets/app_bg.jpeg
    - lib/assets/hush_logo.svg