// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
<<<<<<< HEAD
        return macos;
      case TargetPlatform.windows:
        return windows;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> 84ab20b10485b155bd0724e12a758ef94078a661
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtArjwemgz6faAT8iiUcEuo1IbUbzZ_HE',
    appId: '1:621906786515:web:17ead0d224d322012dbc26',
    messagingSenderId: '621906786515',
    projectId: 'project-gemini-45a06',
    authDomain: 'project-gemini-45a06.firebaseapp.com',
    databaseURL: 'https://project-gemini-45a06-default-rtdb.firebaseio.com',
    storageBucket: 'project-gemini-45a06.appspot.com',
    measurementId: 'G-C5MN8GWZDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk8QAdNXZRBy4W_2NM7ymNNbFSIaxMG-8',
<<<<<<< HEAD
    appId: '1:621906786515:android:ed3f2107b13e16482dbc26',
=======
    appId: '1:621906786515:android:7aa7279646020f252dbc26',
>>>>>>> 84ab20b10485b155bd0724e12a758ef94078a661
    messagingSenderId: '621906786515',
    projectId: 'project-gemini-45a06',
    databaseURL: 'https://project-gemini-45a06-default-rtdb.firebaseio.com',
    storageBucket: 'project-gemini-45a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67XG4zoor-ZpQq2FjljKGdvy4uYY8934',
<<<<<<< HEAD
    appId: '1:621906786515:ios:c042ae79b5dbbb6e2dbc26',
=======
    appId: '1:621906786515:ios:76ac6d671f05af6d2dbc26',
>>>>>>> 84ab20b10485b155bd0724e12a758ef94078a661
    messagingSenderId: '621906786515',
    projectId: 'project-gemini-45a06',
    databaseURL: 'https://project-gemini-45a06-default-rtdb.firebaseio.com',
    storageBucket: 'project-gemini-45a06.appspot.com',
    androidClientId: '621906786515-3jsp8834bqoru55mlujgdn1ctkr7n25e.apps.googleusercontent.com',
<<<<<<< HEAD
    iosClientId: '621906786515-a6rnpl15dop3fedohobbj0bs3p42fvhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hushhForStudentsIos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67XG4zoor-ZpQq2FjljKGdvy4uYY8934',
    appId: '1:621906786515:ios:c042ae79b5dbbb6e2dbc26',
    messagingSenderId: '621906786515',
    projectId: 'project-gemini-45a06',
    databaseURL: 'https://project-gemini-45a06-default-rtdb.firebaseio.com',
    storageBucket: 'project-gemini-45a06.appspot.com',
    androidClientId: '621906786515-3jsp8834bqoru55mlujgdn1ctkr7n25e.apps.googleusercontent.com',
    iosClientId: '621906786515-a6rnpl15dop3fedohobbj0bs3p42fvhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hushhForStudentsIos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtArjwemgz6faAT8iiUcEuo1IbUbzZ_HE',
    appId: '1:621906786515:web:8ab3492bd0ccbde22dbc26',
    messagingSenderId: '621906786515',
    projectId: 'project-gemini-45a06',
    authDomain: 'project-gemini-45a06.firebaseapp.com',
    databaseURL: 'https://project-gemini-45a06-default-rtdb.firebaseio.com',
    storageBucket: 'project-gemini-45a06.appspot.com',
    measurementId: 'G-3C1RJBVTEW',
  );

}
=======
    iosClientId: '621906786515-6slo7tasho3b10bbrb2ptv173b0v8k3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hfsFlutter',
  );
}
>>>>>>> 84ab20b10485b155bd0724e12a758ef94078a661
